version: "3.8"

services:

  auth_service:
    image: auth_service
    container_name: auth_service
    hostname: ${AUTH_SERVICE_HOST}
    build:
      context: ./authorization/
      dockerfile: Dockerfile
    restart: always
    environment:
      ORDERING_DB_HOST: ${AUTH_DB_HOST}
      ORDERING_DB_PORT: ${AUTH_DB_PORT}
      ORDERING_SERVICE_PORT: ${AUTH_SERVICE_PORT}
    depends_on:
      - auth_db
    networks:
      - network

  accommodations_service:
    image: accommodations_service
    container_name: accommodations_service
    hostname: ${ACCOMMODATIONS_SERVICE_HOST}
    build:
      context: ./accommodations-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      ORDERING_DB_HOST: ${ACCOMMODATIONS_DB_HOST}
      ORDERING_DB_PORT: ${ACCOMMODATIONS_DB_PORT}
      ORDERING_SERVICE_PORT: ${ACCOMMODATIONS_SERVICE_PORT}
    depends_on:
      - accommodations_db
    networks:
      - network

  api_gateway:
    build:
      context: ./api_gateway/
      dockerfile: Dockerfile
    container_name: api_gateway
    hostname: ${API_GATEWAY_HOST}
    restart: on-failure
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      - auth_service
      - accommodations_service
    networks:
      - network

  auth_db:
    image: mongo
    container_name: auth_db
    restart: on-failure
    networks:
      - network

  accommodations_db:
    image: mongo
    container_name: accommodations_db
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge